name: interval_timer_app_v3
description: "3+ version of timer project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  shared_preferences: ^2.3.0

  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5

  adaptive_theme: ^3.6.0

  material_symbols_icons: ^4.2771.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
flutter_intl:
  enabled: true
